apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-mcp
  namespace: observability-mcp
  labels:
    app.kubernetes.io/name: observability-mcp
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOST: "0.0.0.0"