apiVersion: v1
kind: Service
metadata:
  name: observability-mcp
  namespace: observability-mcp
  labels:
    app.kubernetes.io/name: observability-mcp
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
      appProtocol: HTTP
  selector:
    app.kubernetes.io/name: observability-mcp
